function [fitresult, gof] = conti_K_fits(P_vals, k_5, k_10, k_15)
%CREATEFITS(P_VALS,K_10,K_5,K_15)
%  Create fits.
%
%  Data for 'fit_10' fit:
%      X Input : P_vals
%      Y Output: k_10
%  Data for 'fit_5' fit:
%      X Input : P_vals
%      Y Output: k_5
%  Data for 'fit_5_alpha' fit:
%      X Input : P_vals
%      Y Output: k_5
%  Data for 'fit_15' fit:
%      X Input : P_vals
%      Y Output: k_15
%  Data for 'fit_15_alpha' fit:
%      X Input : P_vals
%      Y Output: k_15
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Apr-2023 14:49:33

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 5, 1 );
gof = struct( 'sse', cell( 5, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'fit_10'.
[xData, yData] = prepareCurveData( P_vals, k_10 );

% Set up fittype and options.
ft = fittype( '(1.381e-23)*283.15/(6.626e-34)*exp(-(-283.15*DSo+DHo+DVo*(P-0.101325))/(8.3145*283.15))', 'independent', 'P', 'dependent', 'k' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [10000 -200 -Inf];                 % DHo DSo DVo
opts.StartPoint = [30000 0 0.678735154857773];
opts.Upper = [50000 200 Inf];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

%% Fit: 'fit_5'.
[xData, yData] = prepareCurveData( P_vals, k_5 );

% Set up fittype and options.
ft = fittype( '(1.381e-23)*278.15/(6.626e-34)*exp(-(DCp*-5-DCp*278.15*log(278.15/283.15)-278.15*DSo+DHo+42.18*(P-0.101325))/(8.3145*278.15))', 'independent', 'P', 'dependent', 'k' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-10000 10000 -200];       % DCp DHo DSo
opts.StartPoint = [-5000 50000 0];
opts.Upper = [-500 100000 200];

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

%% Fit: 'fit_5_alpha'.
[xData, yData] = prepareCurveData( P_vals, k_5 );

% Set up fittype and options.
ft = fittype( '(1.381e-23)*278.15/(6.626e-34)*exp(-(-5834*-5+5834*278.15*log(278.15/283.15)-278.15*-33.32+DHo+42.18*(P-0.101325)+Da*(P-0.101325)*-5)/(8.3145*278.15))', 'independent', 'P', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.27692298496089 -1.2];

% Fit model to data.
[fitresult{3}, gof(3)] = fit( xData, yData, ft, opts );

%% Fit: 'fit_15'.
[xData, yData] = prepareCurveData( P_vals, k_15 );

% Set up fittype and options.
ft = fittype( '(1.381e-23)*288.15/(6.626e-34)*exp(-(DCp*5-DCp*288.15*log(288.15/283.15)-288.15*DSo+DHo+42.18*(P-0.101325))/(8.3145*288.15))', 'independent', 'P', 'dependent', 'k' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-10000 10000 -200];       % DCp DHo DSo
opts.StartPoint = [-5000 50000 0];
opts.Upper = [-500 100000 200];

% Fit model to data.
[fitresult{4}, gof(4)] = fit( xData, yData, ft, opts );

%% Fit: 'fit_15_alpha'.
[xData, yData] = prepareCurveData( P_vals, k_15 );

% Set up fittype and options.
ft = fittype( '(1.381e-23)*288.15/(6.626e-34)*exp(-(-5923*5+5923*288.15*log(288.15/283.15)-288.15*-36.92+DHo+42.18*(P-0.101325)+Da*(P-0.101325)*5)/(8.3145*288.15))', 'independent', 'P', 'dependent', 'k' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.547215529963803 0.706046088019609];    % DHo Da

% Fit model to data.
[fitresult{5}, gof(5)] = fit( xData, yData, ft, opts );


