function [fitresult, gof] = fit_to_pressure(P, k)
%CREATEFITS(P_VALS_SI,RATE_VALS,T_VALS_62,RATE_VALS_62,P_SPYRO,K_SPYRO)
%  Create fits.
%
%  Data for 'fit_to_pressure' fit:
%      X Input : P
%      Y Output: k
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Apr-2023 11:06:31

%% Fit: 'fit_to_pressure'.
[xData, yData] = prepareCurveData( P, k );

% Set up fittype and options.
ft = fittype( '(1.3807e-23)*297.15/(6.6261e-34)*exp(-(DCp*(297.15-273.15)-DCp*297.15*log(297.15/273.15)+DHo-297.15*DSo+DVo*(P*(1e6)-101325))/(8.3145*297.15))', 'independent', 'P', 'dependent', 'k' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-10000 20000 -200 0];         % DCp DHo DSo DVo
opts.StartPoint = [-5000 30000 0 4e-05];
opts.Upper = [0 100000 200 0.0002];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );


