function [fitresult, gof] = fit_to_temperature(T, k)
%CREATEFIT(T_CONTIK,K_CONTIK)
%  Create a fit.
%
%  Data for 'fit_to_temperature' fit:
%      X Input : T_ContiK
%      Y Output: k_ContiK
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Apr-2023 11:57:25


%% Fit: 'fit_to_temperature'.
[xData, yData] = prepareCurveData( T, k );

% Set up fittype and options.
ft = fittype( '(1.3807e-23)*(T+273.15)/(6.6261e-34)*exp(-(DCp*(T+273.15-273.15)-DCp*(T+273.15)*log((T+273.15)/273.15)+DHo-(T+273.15)*DSo)/(8.3145*(T+273.15)))', 'independent', 'T', 'dependent', 'k' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-10000 10000 -250];       % DCp DHo DSo
opts.StartPoint = [-4000 50000 0];
opts.Upper = [-500 100000 250];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'fit_to_temperature' );
h = plot( fitresult, xData, yData );
legend( h, 'k_ContiK vs. T_ContiK', 'fit_to_temperature', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'T_ContiK', 'Interpreter', 'none' );
ylabel( 'k_ContiK', 'Interpreter', 'none' );
grid on


